apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi #50 minikube 10 azure
  storageClassName: standard  # from "standard" minikube to "managed-csi" azure