apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi #50 minikube 10 azure
  storageClassName: managed-csi # from "standard" minikube to "managed-csi" azure
  #test